Eliminar la ruta de ordenes en el layout app
Introduje por error la ruta ordenes.view en el commit aeca2dcb030c66d2544598ee33ed33dfe0d93874.

Error: Route [ordenes.view] not defined.